require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
end

target 'App' do
  capacitor_pods

  # @capacitor-community/admob 6.2.0 usa l'API vecchia del consenso Google
  # (UMPConsentStatus). In GoogleUserMessagingPlatform 3.0 quei simboli sono
  # stati rinominati e la compilazione fallisce con:
  #   'UMPConsentStatus' has been renamed to 'ConsentStatus'
  # Il plugin fissa Google-Mobile-Ads-SDK a 11.3.0, che pero' accetta UMP >= 2.0:
  # senza questo vincolo CocoaPods tira giu' la 3.x e il build si rompe.
  pod 'GoogleUserMessagingPlatform', '~> 2.0'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
